# codemagic.yaml
workflows:
  ios-testflight:
    name: Chat Buddy → TestFlight
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: 15.4
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
    scripts:
      - name: Install deps
        script: |
          flutter pub get
          cd ios && pod install --repo-update
      - name: Build IPA
        script: |
          flutter build ipa --release \
            --export-options-plist=ios/ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: api_key
        submit_to_testflight: true
